/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __esm = (fn, res) => function __init() {
  return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/providers/codebuddy/env.ts
function buildChildEnv(opts) {
  const env = {};
  for (const key of ENV_PASSTHROUGH) {
    const val = process.env[key];
    if (val !== void 0) {
      env[key] = val;
    }
  }
  for (const [key, val] of Object.entries(process.env)) {
    if ((key.startsWith("CODEBUDDY_") || key.startsWith("WORKBUDDY_")) && val !== void 0) {
      env[key] = val;
    }
  }
  return env;
}
var ENV_PASSTHROUGH;
var init_env = __esm({
  "src/providers/codebuddy/env.ts"() {
    ENV_PASSTHROUGH = [
      "PATH",
      "HOME",
      "USERPROFILE",
      "HTTP_PROXY",
      "HTTPS_PROXY",
      "NO_PROXY",
      "http_proxy",
      "https_proxy",
      "no_proxy",
      "NODE_EXTRA_CA_CERTS",
      "NODE_OPTIONS",
      "LANG",
      "TERM",
      "SHELL",
      "TMPDIR",
      "TEMP",
      "TMP"
    ];
  }
});

// src/providers/codebuddy/transport-print.ts
var import_child_process3, import_readline2, PrintTransport;
var init_transport_print = __esm({
  "src/providers/codebuddy/transport-print.ts"() {
    import_child_process3 = require("child_process");
    import_readline2 = require("readline");
    init_env();
    PrintTransport = class {
      async execute(cliPath, prompt, opts) {
        const args = this.buildArgs(opts, prompt);
        const env = buildChildEnv(opts);
        return new Promise((resolve) => {
          const proc = (0, import_child_process3.spawn)(cliPath, args, {
            cwd: opts.cwd,
            env,
            stdio: ["pipe", "pipe", "pipe"]
          });
          let stdout = "";
          let stderr = "";
          const streamEvents = [];
          const outRl = (0, import_readline2.createInterface)({ input: proc.stdout });
          outRl.on("line", (line) => {
            if (!line.trim()) return;
            stdout += line + "\n";
            try {
              streamEvents.push(JSON.parse(line));
            } catch {
            }
          });
          const errRl = (0, import_readline2.createInterface)({ input: proc.stderr });
          errRl.on("line", (line) => {
            stderr += line + "\n";
          });
          proc.on("close", (code) => {
            resolve({ exitCode: code, stdout: stdout.trim(), stderr: stderr.trim(), streamEvents });
          });
          proc.on("error", (err) => {
            resolve({ exitCode: -1, stdout, stderr: stderr + err.message, streamEvents });
          });
        });
      }
      buildArgs(opts, prompt) {
        const args = ["-p", prompt, "--output-format", "stream-json"];
        if (opts.model) args.push("--model", opts.model);
        if (opts.permissionMode) args.push("--permission-mode", opts.permissionMode);
        if (opts.systemPromptFile) args.push("--system-prompt-file", opts.systemPromptFile);
        if (opts.appendSystemPrompt) args.push("--append-system-prompt", opts.appendSystemPrompt);
        if (opts.mcpConfigPath) args.push("--mcp-config", opts.mcpConfigPath);
        if (opts.addDirs && opts.addDirs.length > 0) args.push("--add-dir", ...opts.addDirs);
        if (opts.allowedTools && opts.allowedTools.length > 0) args.push("--allowedTools", ...opts.allowedTools);
        if (opts.disallowedTools && opts.disallowedTools.length > 0) args.push("--disallowedTools", ...opts.disallowedTools);
        if (opts.maxTurns && opts.maxTurns > 0) args.push("--max-turns", String(opts.maxTurns));
        if (opts.effort) args.push("--effort", opts.effort);
        if (opts.debug) args.push("--debug");
        return args;
      }
    };
  }
});

// src/features/chat/rendering/DiffRenderer.ts
var DiffRenderer;
var init_DiffRenderer = __esm({
  "src/features/chat/rendering/DiffRenderer.ts"() {
    DiffRenderer = class {
      static render(segments, containerEl) {
        containerEl.empty();
        containerEl.addClass("codebuddian-diff");
        for (const seg of segments) {
          const span = containerEl.createSpan({
            cls: `codebuddian-diff-${seg.type}`
          });
          span.setText(seg.text);
        }
      }
      static computeDiff(original, modified) {
        const origLines = original.split("\n");
        const modLines = modified.split("\n");
        const segments = [];
        const lcs = this.lcs(origLines, modLines);
        let oi = 0, mi = 0, li = 0;
        while (oi < origLines.length || mi < modLines.length) {
          if (li < lcs.length && oi < origLines.length && mi < modLines.length && origLines[oi] === lcs[li] && modLines[mi] === lcs[li]) {
            segments.push({ type: "equal", text: lcs[li] + "\n" });
            oi++;
            mi++;
            li++;
          } else if (oi < origLines.length && (li >= lcs.length || origLines[oi] !== lcs[li])) {
            segments.push({ type: "delete", text: origLines[oi] + "\n" });
            oi++;
          } else if (mi < modLines.length && (li >= lcs.length || modLines[mi] !== lcs[li])) {
            segments.push({ type: "insert", text: modLines[mi] + "\n" });
            mi++;
          } else {
            oi++;
            mi++;
          }
        }
        return segments;
      }
      static lcs(a, b) {
        const m = a.length, n = b.length;
        const dp = Array.from({ length: m + 1 }, () => Array(n + 1).fill(0));
        for (let i2 = 1; i2 <= m; i2++) {
          for (let j2 = 1; j2 <= n; j2++) {
            dp[i2][j2] = a[i2 - 1] === b[j2 - 1] ? dp[i2 - 1][j2 - 1] + 1 : Math.max(dp[i2 - 1][j2], dp[i2][j2 - 1]);
          }
        }
        const result = [];
        let i = m, j = n;
        while (i > 0 && j > 0) {
          if (a[i - 1] === b[j - 1]) {
            result.unshift(a[i - 1]);
            i--;
            j--;
          } else if (dp[i - 1][j] > dp[i][j - 1]) {
            i--;
          } else {
            j--;
          }
        }
        return result;
      }
    };
  }
});

// src/features/inline-edit/ui/InlineEditModal.ts
var InlineEditModal_exports = {};
__export(InlineEditModal_exports, {
  InlineEditModal: () => InlineEditModal
});
var import_obsidian5, InlineEditModal;
var init_InlineEditModal = __esm({
  "src/features/inline-edit/ui/InlineEditModal.ts"() {
    import_obsidian5 = require("obsidian");
    init_transport_print();
    init_DiffRenderer();
    InlineEditModal = class extends import_obsidian5.Modal {
      originalText;
      modifiedText = "";
      diffSegments = [];
      prompt;
      settings;
      cliPath;
      vaultPath;
      onApply;
      component;
      constructor(app, opts) {
        super(app);
        this.originalText = opts.originalText;
        this.prompt = opts.prompt;
        this.settings = opts.settings;
        this.cliPath = opts.cliPath;
        this.vaultPath = opts.vaultPath;
        this.onApply = opts.onApply;
        this.component = new import_obsidian5.Component();
      }
      onOpen() {
        const { contentEl } = this;
        contentEl.addClass("codebuddian-inline-edit-modal");
        contentEl.createEl("h2", { text: "Inline Edit" });
        contentEl.createEl("h3", { text: "Original" });
        const origEl = contentEl.createDiv({ cls: "codebuddian-inline-original" });
        origEl.setText(this.originalText);
        contentEl.createEl("h3", { text: `Instruction: ${this.prompt}` });
        const statusEl = contentEl.createDiv({ text: "\u23F3 Running CodeBuddy\u2026", cls: "codebuddian-inline-status" });
        this.runEdit().then((result) => {
          statusEl.setText("");
          if (result.exitCode === 0 && result.stdout) {
            this.modifiedText = result.stdout;
            this.diffSegments = DiffRenderer.computeDiff(this.originalText, this.modifiedText);
            contentEl.createEl("h3", { text: "Changes" });
            const diffEl = contentEl.createDiv({ cls: "codebuddian-inline-diff" });
            DiffRenderer.render(this.diffSegments, diffEl);
            const btnRow = contentEl.createDiv({ cls: "codebuddian-inline-buttons" });
            const applyBtn = btnRow.createEl("button", { text: "\u2705 Apply", cls: "mod-cta" });
            applyBtn.addEventListener("click", () => {
              this.onApply(this.modifiedText);
              this.close();
            });
            const cancelBtn = btnRow.createEl("button", { text: "\u274C Cancel" });
            cancelBtn.addEventListener("click", () => this.close());
          } else {
            statusEl.setText(`\u274C Error: ${result.stderr || "Unknown error"}`);
            const closeBtn = contentEl.createEl("button", { text: "Close" });
            closeBtn.addEventListener("click", () => this.close());
          }
        });
      }
      onClose() {
        this.contentEl.empty();
      }
      async runEdit() {
        const transport = new PrintTransport();
        const fullPrompt = `Edit the following text according to the instruction. Return ONLY the modified text, nothing else.

Instruction: ${this.prompt}

Original text:
${this.originalText}`;
        return transport.execute(this.cliPath, fullPrompt, {
          cwd: this.vaultPath,
          model: this.settings.model || void 0,
          permissionMode: this.settings.permissionMode
        });
      }
    };
  }
});

// src/main.ts
var main_exports = {};
__export(main_exports, {
  CodebuddianPlugin: () => CodebuddianPlugin,
  default: () => main_default
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/app/settings/defaultSettings.ts
var DEFAULT_SETTINGS = {
  cliPath: "",
  model: "",
  permissionMode: "default",
  systemPromptFile: "",
  appendSystemPrompt: "",
  mcpConfigPath: "",
  addDirs: [],
  maxTurns: 0,
  effort: "medium",
  allowedTools: [],
  disallowedTools: [],
  autoDetectCli: true,
  theme: "system",
  fontSize: 14,
  showThinking: false,
  autoScroll: true,
  debugMode: false,
  verboseMode: false,
  includePartialMessages: false,
  strictMcpConfig: false
};

// src/features/chat/CodebuddianView.ts
var import_obsidian2 = require("obsidian");

// src/features/chat/constants.ts
var CHAT_VIEW_TYPE = "codebuddian-chat";
var CHAT_ICON = "message-circle";
var AVAILABLE_MODELS = [
  { id: "", label: "Default (CLI default)" },
  { id: "claude-opus-4.8", label: "Claude Opus 4.8" },
  { id: "claude-sonnet-4.7", label: "Claude Sonnet 4.7" },
  { id: "gpt-5.5", label: "GPT-5.5" },
  { id: "gpt-5.5-mini", label: "GPT-5.5 Mini" },
  { id: "kimi-k2.6", label: "Kimi K2.6" },
  { id: "deepseek-v4-pro", label: "DeepSeek V4 Pro" },
  { id: "deepseek-v4-lite", label: "DeepSeek V4 Lite" },
  { id: "gemini-3.5-pro", label: "Gemini 3.5 Pro" },
  { id: "qwen-4.5-max", label: "Qwen 4.5 Max" }
];
var EFFORT_OPTIONS = [
  { id: "low", label: "Low" },
  { id: "medium", label: "Medium" },
  { id: "high", label: "High" }
];

// src/features/chat/state/types.ts
function createEmptyTab(id) {
  return {
    id,
    title: "New chat",
    messages: [],
    status: "idle",
    permissionMode: "default",
    isPlanMode: false,
    sessionId: null,
    model: "",
    effort: "medium",
    createdAt: Date.now(),
    updatedAt: Date.now()
  };
}

// src/features/chat/state/ChatState.ts
var ChatStateManager = class {
  state = {
    activeTabId: null,
    tabs: [],
    inputValue: "",
    isInputFocused: false
  };
  listeners = /* @__PURE__ */ new Set();
  getState() {
    return this.state;
  }
  subscribe(listener) {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }
  notify() {
    this.listeners.forEach((l) => l());
  }
  addTab() {
    const id = `tab-${Date.now()}`;
    const tab = createEmptyTab(id);
    this.state.tabs.push(tab);
    this.state.activeTabId = id;
    this.notify();
    return tab;
  }
  removeTab(id) {
    this.state.tabs = this.state.tabs.filter((t2) => t2.id !== id);
    if (this.state.activeTabId === id) {
      this.state.activeTabId = this.state.tabs.length > 0 ? this.state.tabs[0].id : null;
    }
    this.notify();
  }
  setActiveTab(id) {
    this.state.activeTabId = id;
    this.notify();
  }
  getActiveTab() {
    return this.state.tabs.find((t2) => t2.id === this.state.activeTabId);
  }
  updateTab(id, update) {
    const tab = this.state.tabs.find((t2) => t2.id === id);
    if (tab) {
      Object.assign(tab, update, { updatedAt: Date.now() });
      this.notify();
    }
  }
  addMessage(tabId, message) {
    const tab = this.state.tabs.find((t2) => t2.id === tabId);
    if (tab) {
      tab.messages.push(message);
      tab.updatedAt = Date.now();
      this.notify();
    }
  }
  updateLastAssistantMessage(tabId, content) {
    const tab = this.state.tabs.find((t2) => t2.id === tabId);
    if (tab) {
      const lastAssistant = [...tab.messages].reverse().find((m) => m.role === "assistant");
      if (lastAssistant) {
        lastAssistant.content = content;
        lastAssistant.isStreaming = true;
        tab.updatedAt = Date.now();
        this.notify();
      }
    }
  }
  finalizeLastAssistantMessage(tabId) {
    const tab = this.state.tabs.find((t2) => t2.id === tabId);
    if (tab) {
      const lastAssistant = [...tab.messages].reverse().find((m) => m.role === "assistant");
      if (lastAssistant) {
        lastAssistant.isStreaming = false;
        tab.updatedAt = Date.now();
        tab.status = "idle";
        this.notify();
      }
    }
  }
  setInputValue(value) {
    this.state.inputValue = value;
  }
  clearTabs() {
    this.state.tabs = [];
    this.state.activeTabId = null;
    this.notify();
  }
};

// src/features/chat/tabs/Tab.ts
var Tab = class {
  constructor(id, stateManager) {
    this.id = id;
    this.stateManager = stateManager;
  }
  get data() {
    return this.stateManager.getState().tabs.find((t2) => t2.id === this.id);
  }
  isActive() {
    return this.stateManager.getState().activeTabId === this.id;
  }
  activate() {
    this.stateManager.setActiveTab(this.id);
  }
  close() {
    this.stateManager.removeTab(this.id);
  }
};

// src/features/chat/tabs/TabManager.ts
var TabManager = class {
  constructor(stateManager) {
    this.stateManager = stateManager;
  }
  tabs = /* @__PURE__ */ new Map();
  createTab() {
    const data = this.stateManager.addTab();
    const tab = new Tab(data.id, this.stateManager);
    this.tabs.set(data.id, tab);
    return tab;
  }
  getTab(id) {
    return this.tabs.get(id);
  }
  getActiveTab() {
    const activeId = this.stateManager.getState().activeTabId;
    return activeId ? this.tabs.get(activeId) : void 0;
  }
  closeTab(id) {
    this.tabs.delete(id);
    this.stateManager.removeTab(id);
  }
  getAllTabs() {
    return Array.from(this.tabs.values());
  }
  ensureAtLeastOneTab() {
    if (this.tabs.size === 0) {
      return this.createTab();
    }
    return this.getActiveTab() || this.createTab();
  }
};

// src/features/chat/tabs/TabBar.ts
var TabBar = class {
  containerEl;
  onTabClick;
  onTabClose;
  onNewTab;
  constructor(containerEl, callbacks) {
    this.containerEl = containerEl;
    this.onTabClick = callbacks.onTabClick;
    this.onTabClose = callbacks.onTabClose;
    this.onNewTab = callbacks.onNewTab;
  }
  render(tabs) {
    this.containerEl.empty();
    this.containerEl.addClass("codebuddian-tab-bar");
    for (const tab of tabs) {
      const tabEl = this.containerEl.createDiv({
        cls: `codebuddian-tab ${tab.isActive ? "active" : ""}`
      });
      tabEl.createSpan({ text: tab.title, cls: "codebuddian-tab-title" });
      tabEl.addEventListener("click", () => this.onTabClick(tab.id));
      const closeBtn = tabEl.createSpan({ cls: "codebuddian-tab-close", text: "\xD7" });
      closeBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        this.onTabClose(tab.id);
      });
    }
    const newTabBtn = this.containerEl.createDiv({ cls: "codebuddian-tab-new" });
    newTabBtn.setText("+");
    newTabBtn.addEventListener("click", () => this.onNewTab());
  }
};

// src/features/chat/rendering/MessageRenderer.ts
var import_obsidian = require("obsidian");

// src/core/tools/toolIcons.ts
var TOOL_ICONS = {
  Read: "\u{1F4D6}",
  Write: "\u270F\uFE0F",
  Edit: "\u{1F527}",
  Bash: "\u{1F4BB}",
  Glob: "\u{1F50D}",
  Grep: "\u{1F50E}",
  WebFetch: "\u{1F310}",
  WebSearch: "\u{1F52C}",
  ImageGen: "\u{1F3A8}"
};

// src/core/tools/toolInput.ts
function formatToolInput(tool, args) {
  const entries = Object.entries(args);
  if (entries.length === 0) return `${tool}()`;
  const formatted = entries.map(([k, v]) => {
    const val = typeof v === "string" ? v : JSON.stringify(v);
    const truncated = val.length > 200 ? val.slice(0, 200) + "..." : val;
    return `${k}: ${truncated}`;
  });
  return `${tool}(${formatted.join(", ")})`;
}

// src/core/tools/toolResultContent.ts
function formatToolResult(tool, result, ok) {
  if (!ok) {
    return `\u274C ${tool} failed: ${result}`;
  }
  const truncated = result.length > 2e3 ? result.slice(0, 2e3) + "\n... (truncated)" : result;
  return truncated;
}

// src/features/chat/rendering/ToolCallRenderer.ts
var ToolCallRenderer = class {
  containerEl;
  constructor(containerEl) {
    this.containerEl = containerEl;
  }
  render(toolCall, result) {
    const el = this.containerEl.createDiv({ cls: "codebuddian-tool-call" });
    const headerEl = el.createDiv({ cls: "codebuddian-tool-header" });
    const icon = TOOL_ICONS[toolCall.tool] || "\u{1F527}";
    headerEl.createSpan({ text: `${icon} ${toolCall.tool}`, cls: "codebuddian-tool-name" });
    const statusColors = {
      pending: "\u{1F7E1}",
      running: "\u{1F535}",
      completed: "\u{1F7E2}",
      error: "\u{1F534}",
      approval_needed: "\u26A0\uFE0F"
    };
    headerEl.createSpan({
      text: statusColors[toolCall.status] || "\u26AA",
      cls: "codebuddian-tool-status"
    });
    const argsEl = el.createDiv({ cls: "codebuddian-tool-args" });
    const inputStr = formatToolInput(toolCall.tool, toolCall.args);
    const argsPre = argsEl.createEl("pre", { cls: "codebuddian-tool-args-pre" });
    argsPre.createEl("code", { text: inputStr });
    if (result) {
      const resultEl = el.createDiv({ cls: "codebuddian-tool-result" });
      const resultStr = formatToolResult(toolCall.tool, result.result || "", result.ok);
      const resultPre = resultEl.createEl("pre", { cls: "codebuddian-tool-result-pre" });
      resultPre.createEl("code", { text: resultStr });
    } else if (toolCall.result) {
      const resultEl = el.createDiv({ cls: "codebuddian-tool-result" });
      const resultStr = formatToolResult(toolCall.tool, toolCall.result, toolCall.status !== "error");
      const resultPre = resultEl.createEl("pre", { cls: "codebuddian-tool-result-pre" });
      resultPre.createEl("code", { text: resultStr });
    }
    return el;
  }
  renderApprovalCard(toolCall, onApprove, onDeny) {
    const el = this.containerEl.createDiv({ cls: "codebuddian-approval-card" });
    el.createDiv({
      cls: "codebuddian-approval-header",
      text: `\u26A0\uFE0F Approval Required: ${toolCall.tool}`
    });
    const argsEl = el.createDiv({ cls: "codebuddian-approval-args" });
    const inputStr = formatToolInput(toolCall.tool, toolCall.args);
    argsEl.createEl("pre", { text: inputStr });
    const btnRow = el.createDiv({ cls: "codebuddian-approval-buttons" });
    const approveBtn = btnRow.createEl("button", {
      text: "\u2705 Approve",
      cls: "codebuddian-btn codebuddian-btn-approve"
    });
    approveBtn.addEventListener("click", onApprove);
    const denyBtn = btnRow.createEl("button", {
      text: "\u274C Deny",
      cls: "codebuddian-btn codebuddian-btn-deny"
    });
    denyBtn.addEventListener("click", onDeny);
    return el;
  }
};

// src/features/chat/rendering/MessageRenderer.ts
var MessageRenderer = class {
  containerEl;
  component;
  app;
  constructor(containerEl, component, app) {
    this.containerEl = containerEl;
    this.component = component;
    this.app = app;
  }
  renderMessage(message) {
    const msgEl = this.containerEl.createDiv({
      cls: `codebuddian-message codebuddian-message-${message.role}`
    });
    const headerEl = msgEl.createDiv({ cls: "codebuddian-message-header" });
    const roleLabel = message.role === "user" ? "\u{1F464} You" : message.role === "assistant" ? "\u{1F916} CodeBuddy" : "\u2699\uFE0F System";
    headerEl.createSpan({ text: roleLabel, cls: "codebuddian-message-role" });
    headerEl.createSpan({
      text: new Date(message.timestamp).toLocaleTimeString(),
      cls: "codebuddian-message-time"
    });
    if (message.thinkingContent) {
      const thinkingEl = msgEl.createDiv({ cls: "codebuddian-thinking" });
      thinkingEl.createDiv({ cls: "codebuddian-thinking-header", text: "\u{1F4AD} Thinking" });
      thinkingEl.createDiv({ cls: "codebuddian-thinking-content", text: message.thinkingContent });
    }
    if (message.content) {
      const contentEl = msgEl.createDiv({ cls: "codebuddian-message-content" });
      if (message.role === "assistant") {
        import_obsidian.MarkdownRenderer.render(
          this.app,
          message.content,
          contentEl,
          "",
          this.component
        );
      } else {
        contentEl.setText(message.content);
      }
    }
    if (message.toolCalls && message.toolCalls.length > 0) {
      const toolRenderer = new ToolCallRenderer(msgEl);
      for (const toolCall of message.toolCalls) {
        toolRenderer.render(toolCall);
      }
    }
    if (message.isStreaming) {
      const streamEl = msgEl.createDiv({ cls: "codebuddian-streaming-indicator" });
      streamEl.createSpan({ text: "\u25CF" });
      streamEl.createSpan({ text: "\u25CF" });
      streamEl.createSpan({ text: "\u25CF" });
    }
    return msgEl;
  }
  renderMessages(messages) {
    this.containerEl.empty();
    for (const message of messages) {
      this.renderMessage(message);
    }
  }
};

// src/features/chat/controllers/StreamController.ts
var StreamController = class {
  constructor(stateManager) {
    this.stateManager = stateManager;
  }
  currentAssistantContent = "";
  handleEvent(tabId, event) {
    switch (event.type) {
      case "message": {
        const data = event.data;
        if (data.role === "assistant" || data.delta) {
          if (data.delta) {
            this.currentAssistantContent += data.delta;
          } else if (data.content) {
            this.currentAssistantContent = data.content;
          }
          this.stateManager.updateLastAssistantMessage(tabId, this.currentAssistantContent);
        } else if (data.role === "user" && data.content) {
          const userMsg = {
            id: `msg-${Date.now()}`,
            role: "user",
            content: data.content,
            timestamp: event.timestamp
          };
          this.stateManager.addMessage(tabId, userMsg);
        }
        break;
      }
      case "thinking": {
        const data = event.data;
        const tab = this.stateManager.getActiveTab();
        if (tab) {
          const lastAssistant = [...tab.messages].reverse().find((m) => m.role === "assistant");
          if (lastAssistant) {
            lastAssistant.thinkingContent = data.content || "";
            this.stateManager.updateTab(tabId, {});
          }
        }
        break;
      }
      case "tool_use": {
        const data = event.data;
        if (data.id && data.tool) {
          const tab = this.stateManager.getActiveTab();
          if (tab && tab.messages.length > 0) {
            const lastMsg = tab.messages[tab.messages.length - 1];
            if (!lastMsg.toolCalls) lastMsg.toolCalls = [];
            lastMsg.toolCalls.push({
              id: data.id,
              tool: data.tool,
              args: data.args || {},
              status: "running"
            });
            this.stateManager.updateTab(tabId, {});
          }
        }
        break;
      }
      case "tool_result": {
        const data = event.data;
        if (data.id) {
          const tab = this.stateManager.getActiveTab();
          if (tab && tab.messages.length > 0) {
            const lastMsg = tab.messages[tab.messages.length - 1];
            if (lastMsg.toolCalls) {
              const toolCall = lastMsg.toolCalls.find((tc) => tc.id === data.id);
              if (toolCall) {
                toolCall.status = data.ok ? "completed" : "error";
                toolCall.result = data.result;
                toolCall.error = data.error;
                this.stateManager.updateTab(tabId, {});
              }
            }
          }
        }
        break;
      }
      case "approval": {
        this.stateManager.updateTab(tabId, { status: "waiting_approval" });
        break;
      }
      case "turn_end":
      case "end": {
        if (this.currentAssistantContent) {
          this.stateManager.finalizeLastAssistantMessage(tabId);
          this.currentAssistantContent = "";
        }
        break;
      }
      case "error": {
        const data = event.data;
        const errorMsg = {
          id: `msg-${Date.now()}`,
          role: "system",
          content: `\u274C Error: ${data.message || data.stderr || "Unknown error"}`,
          timestamp: event.timestamp
        };
        this.stateManager.addMessage(tabId, errorMsg);
        this.stateManager.updateTab(tabId, { status: "error" });
        break;
      }
    }
  }
  startNewTurn() {
    this.currentAssistantContent = "";
  }
};

// src/features/chat/controllers/ConversationController.ts
var ConversationController = class {
  constructor(stateManager) {
    this.stateManager = stateManager;
    this.streamController = new StreamController(stateManager);
  }
  sessionHandle = null;
  streamController;
  runtime = null;
  setRuntime(runtime) {
    this.runtime = runtime;
  }
  async sendMessage(text, mentions, instruction) {
    const tab = this.stateManager.getActiveTab();
    if (!tab) return;
    const userMsg = {
      id: `msg-${Date.now()}`,
      role: "user",
      content: text,
      timestamp: Date.now(),
      mentions,
      instruction
    };
    this.stateManager.addMessage(tab.id, userMsg);
    const assistantMsg = {
      id: `msg-${Date.now() + 1}`,
      role: "assistant",
      content: "",
      timestamp: Date.now() + 1,
      isStreaming: true
    };
    this.stateManager.addMessage(tab.id, assistantMsg);
    this.stateManager.updateTab(tab.id, { status: "streaming" });
    if (!this.sessionHandle && this.runtime) {
      try {
        this.sessionHandle = await this.runtime.start({
          cwd: "",
          // Will be set by main.ts
          model: tab.model || void 0,
          effort: tab.effort || void 0,
          permissionMode: tab.permissionMode
        });
        this.setupEventListeners(tab.id);
      } catch (err) {
        this.stateManager.updateTab(tab.id, { status: "error" });
        const errorMsg = {
          id: `msg-${Date.now()}`,
          role: "system",
          content: `\u274C Failed to start session: ${err instanceof Error ? err.message : String(err)}`,
          timestamp: Date.now()
        };
        this.stateManager.addMessage(tab.id, errorMsg);
        return;
      }
    }
    const input = { text, mentions, instruction };
    this.streamController.startNewTurn();
    try {
      await this.sessionHandle?.send(input);
    } catch (err) {
      this.stateManager.updateTab(tab.id, { status: "error" });
    }
  }
  async cancel() {
    await this.sessionHandle?.cancel();
  }
  async togglePlanMode() {
    const tab = this.stateManager.getActiveTab();
    if (!tab) return;
    this.stateManager.updateTab(tab.id, {
      isPlanMode: !tab.isPlanMode,
      permissionMode: tab.isPlanMode ? "default" : "plan"
    });
  }
  setupEventListeners(tabId) {
    if (!this.sessionHandle) return;
    this.sessionHandle.on("*", (event) => {
      this.streamController.handleEvent(tabId, event);
    });
  }
  getSession() {
    return this.sessionHandle;
  }
  async dispose() {
    await this.sessionHandle?.close();
    this.sessionHandle = null;
  }
};

// src/features/chat/controllers/InputController.ts
var InputController = class {
  textareaEl;
  sendButtonEl;
  conversationController;
  stateManager;
  constructor(textareaEl, sendButtonEl, conversationController, stateManager) {
    this.textareaEl = textareaEl;
    this.sendButtonEl = sendButtonEl;
    this.conversationController = conversationController;
    this.stateManager = stateManager;
    this.setupListeners();
  }
  setupListeners() {
    this.textareaEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.handleSend();
      }
    });
    this.sendButtonEl.addEventListener("click", () => {
      this.handleSend();
    });
    this.textareaEl.addEventListener("input", () => {
      this.stateManager.setInputValue(this.textareaEl.value);
      this.autoResize();
    });
  }
  handleSend() {
    const text = this.textareaEl.value.trim();
    if (!text) return;
    const mentions = this.parseMentions(text);
    const instruction = this.parseInstruction(text);
    const cleanText = this.cleanInputText(text, instruction);
    this.conversationController.sendMessage(cleanText, mentions.length > 0 ? mentions : void 0, instruction || void 0);
    this.textareaEl.value = "";
    this.stateManager.setInputValue("");
    this.resetHeight();
  }
  parseMentions(text) {
    const mentions = [];
    const mentionRegex = /@(\S+)/g;
    let match;
    while ((match = mentionRegex.exec(text)) !== null) {
      const ref = match[1];
      if (ref.startsWith("mcp:")) {
        mentions.push({ type: "mcp", ref: ref.slice(4) });
      } else if (ref.startsWith("agent:")) {
        mentions.push({ type: "agent", ref: ref.slice(6) });
      } else if (ref.startsWith("dir:")) {
        mentions.push({ type: "extDir", ref: ref.slice(4) });
      } else {
        mentions.push({ type: "file", ref });
      }
    }
    return mentions;
  }
  parseInstruction(text) {
    const instructionMatch = text.match(/^#(.+?)(?:\n|$)/);
    return instructionMatch ? instructionMatch[1].trim() : null;
  }
  cleanInputText(text, instruction) {
    if (!instruction) return text;
    return text.replace(/^#.+?(?:\n|$)/, "").trim() || text;
  }
  autoResize() {
    this.textareaEl.style.height = "auto";
    this.textareaEl.style.height = Math.min(this.textareaEl.scrollHeight, 200) + "px";
  }
  resetHeight() {
    this.textareaEl.style.height = "40px";
  }
  focus() {
    this.textareaEl.focus();
  }
  setValue(value) {
    this.textareaEl.value = value;
    this.autoResize();
  }
};

// src/i18n/i18n.ts
var zhCN = {
  "chat.placeholder": "\u5411 CodeBuddy \u53D1\u9001\u6D88\u606F\u2026\uFF08Enter \u53D1\u9001\uFF0CShift+Enter \u6362\u884C\uFF09",
  "chat.send": "\u53D1\u9001",
  "chat.newTab": "\u65B0\u5BF9\u8BDD",
  "chat.cancel": "\u505C\u6B62",
  "chat.planMode": "\u8BA1\u5212\u6A21\u5F0F",
  "chat.model": "\u6A21\u578B",
  "chat.effort": "\u6295\u5165\u5EA6",
  "settings.title": "Codebuddian \u8BBE\u7F6E",
  "settings.cliPath": "CodeBuddy CLI \u8DEF\u5F84",
  "settings.model": "\u6A21\u578B",
  "settings.permissionMode": "\u6743\u9650\u6A21\u5F0F",
  "approval.title": "\u9700\u8981\u5BA1\u6279",
  "approval.approve": "\u6279\u51C6",
  "approval.deny": "\u62D2\u7EDD",
  "error.cliNotFound": "\u672A\u627E\u5230 CodeBuddy CLI\uFF0C\u8BF7\u5728\u8BBE\u7F6E\u4E2D\u914D\u7F6E\u8DEF\u5F84",
  "error.sessionFailed": "\u4F1A\u8BDD\u542F\u52A8\u5931\u8D25"
};
var enUS = {
  "chat.placeholder": "Message CodeBuddy\u2026 (Enter to send, Shift+Enter for newline)",
  "chat.send": "Send",
  "chat.newTab": "New chat",
  "chat.cancel": "Cancel",
  "chat.planMode": "Plan mode",
  "chat.model": "Model",
  "chat.effort": "Effort",
  "settings.title": "Codebuddian Settings",
  "settings.cliPath": "CodeBuddy CLI path",
  "settings.model": "Model",
  "settings.permissionMode": "Permission mode",
  "approval.title": "Approval required",
  "approval.approve": "Approve",
  "approval.deny": "Deny",
  "error.cliNotFound": "CodeBuddy CLI not found, please set path in settings",
  "error.sessionFailed": "Session failed to start"
};
var translations = {
  "zh-CN": zhCN,
  "en": enUS,
  "en-US": enUS
};
var currentLocale = "en";
function setLocale(locale) {
  currentLocale = locale;
}
function t(key, ...args) {
  const dict = translations[currentLocale] || translations["en"];
  let str = dict[key] || key;
  args.forEach((arg, i) => {
    str = str.replace(`{${i}}`, String(arg));
  });
  return str;
}

// src/features/chat/CodebuddianView.ts
var CodebuddianChatView = class extends import_obsidian2.ItemView {
  stateManager;
  tabManager;
  conversationController;
  messageRenderer;
  inputController;
  tabBar;
  messagesContainer;
  textareaEl;
  sendButtonEl;
  modelSelectEl;
  effortSelectEl;
  headerEl;
  runtime = null;
  constructor(leaf) {
    super(leaf);
    this.stateManager = new ChatStateManager();
    this.tabManager = new TabManager(this.stateManager);
    this.conversationController = new ConversationController(this.stateManager);
  }
  getViewType() {
    return CHAT_VIEW_TYPE;
  }
  getDisplayText() {
    return "Codebuddian";
  }
  getIcon() {
    return CHAT_ICON;
  }
  setRuntime(runtime) {
    this.runtime = runtime;
    this.conversationController.setRuntime(runtime);
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("codebuddian-chat-container");
    this.headerEl = container.createDiv({ cls: "codebuddian-header" });
    const brandEl = this.headerEl.createDiv({ cls: "codebuddian-brand" });
    brandEl.createEl("span", { cls: "codebuddian-brand-icon", text: "\u{1F916}" });
    brandEl.createEl("span", { cls: "codebuddian-brand-text", text: "CodeBuddy" });
    const controlsEl = this.headerEl.createDiv({ cls: "codebuddian-header-controls" });
    const modelWrap = controlsEl.createDiv({ cls: "codebuddian-control-group" });
    modelWrap.createEl("label", { cls: "codebuddian-control-label", text: t("chat.model") });
    this.modelSelectEl = modelWrap.createEl("select", { cls: "codebuddian-select" });
    AVAILABLE_MODELS.forEach((m) => {
      const opt = this.modelSelectEl.createEl("option", { text: m.label });
      opt.value = m.id;
    });
    this.modelSelectEl.addEventListener("change", () => {
      const tab = this.stateManager.getActiveTab();
      if (tab) {
        this.stateManager.updateTab(tab.id, { model: this.modelSelectEl.value });
      }
    });
    const effortWrap = controlsEl.createDiv({ cls: "codebuddian-control-group" });
    effortWrap.createEl("label", { cls: "codebuddian-control-label", text: t("chat.effort") });
    this.effortSelectEl = effortWrap.createEl("select", { cls: "codebuddian-select" });
    EFFORT_OPTIONS.forEach((e) => {
      const opt = this.effortSelectEl.createEl("option", { text: e.label });
      opt.value = e.id;
    });
    this.effortSelectEl.addEventListener("change", () => {
      const tab = this.stateManager.getActiveTab();
      if (tab) {
        this.stateManager.updateTab(tab.id, { effort: this.effortSelectEl.value });
      }
    });
    const tabBarEl = container.createDiv({ cls: "codebuddian-tab-bar-container" });
    this.tabBar = new TabBar(tabBarEl, {
      onTabClick: (id) => this.stateManager.setActiveTab(id),
      onTabClose: (id) => this.tabManager.closeTab(id),
      onNewTab: () => this.tabManager.createTab()
    });
    this.messagesContainer = container.createDiv({ cls: "codebuddian-messages" });
    const inputArea = container.createDiv({ cls: "codebuddian-input-area" });
    const toolbar = inputArea.createDiv({ cls: "codebuddian-input-toolbar" });
    const planModeBtn = toolbar.createEl("button", { text: "\u{1F4CB} Plan", cls: "codebuddian-toolbar-btn" });
    planModeBtn.addEventListener("click", () => {
      this.conversationController.togglePlanMode();
    });
    const cancelBtn = toolbar.createEl("button", { text: "\u23F9 Stop", cls: "codebuddian-toolbar-btn" });
    cancelBtn.addEventListener("click", () => {
      this.conversationController.cancel();
    });
    this.textareaEl = inputArea.createEl("textarea", {
      cls: "codebuddian-input",
      attr: {
        placeholder: "Message CodeBuddy\u2026 (Enter to send, Shift+Enter for newline)\nUse @file to mention files, # for instructions, / for commands",
        rows: "1"
      }
    });
    this.sendButtonEl = inputArea.createEl("button", {
      text: "\u27A4",
      cls: "codebuddian-send-btn"
    });
    this.messageRenderer = new MessageRenderer(this.messagesContainer, this, this.app);
    this.inputController = new InputController(
      this.textareaEl,
      this.sendButtonEl,
      this.conversationController,
      this.stateManager
    );
    this.stateManager.subscribe(() => this.render());
    this.tabManager.ensureAtLeastOneTab();
  }
  async onClose() {
    await this.conversationController.dispose();
  }
  render() {
    const state = this.stateManager.getState();
    this.tabBar.render(
      state.tabs.map((t2) => ({
        id: t2.id,
        title: t2.title,
        isActive: t2.id === state.activeTabId
      }))
    );
    const activeTab = this.stateManager.getActiveTab();
    if (activeTab) {
      this.modelSelectEl.value = activeTab.model;
      this.effortSelectEl.value = activeTab.effort;
    }
    if (activeTab) {
      this.messageRenderer.renderMessages(activeTab.messages);
      if (this.messagesContainer) {
        const { scrollTop, scrollHeight, clientHeight } = this.messagesContainer;
        if (scrollHeight - scrollTop - clientHeight < 100) {
          this.messagesContainer.scrollTop = scrollHeight;
        }
      }
    }
  }
};

// src/features/settings/CodebuddianSettingsTab.ts
var import_obsidian3 = require("obsidian");

// src/providers/codebuddy/cli-detect.ts
var import_child_process = require("child_process");
var import_fs = require("fs");
var import_path = require("path");
var CLI_NAMES = ["codebuddy", "cbc"];
var CliDetector = class {
  cachedPath = null;
  async detect() {
    if (this.cachedPath) return this.cachedPath;
    for (const name of CLI_NAMES) {
      try {
        const path = await this.which(name);
        if (path) {
          this.cachedPath = path;
          return path;
        }
      } catch {
      }
    }
    const home = process.env.HOME || "";
    const commonPaths = [
      (0, import_path.join)(home, ".nvm/versions/node/v25.8.1/bin/codebuddy"),
      (0, import_path.join)(home, ".nvm/versions/node/v25.8.1/bin/cbc"),
      "/usr/local/bin/codebuddy",
      "/usr/local/bin/cbc"
    ];
    for (const p of commonPaths) {
      if ((0, import_fs.existsSync)(p)) {
        this.cachedPath = p;
        return p;
      }
    }
    return null;
  }
  which(cmd) {
    return new Promise((resolve) => {
      const isWin = process.platform === "win32";
      const whichCmd = isWin ? "where.exe" : "which";
      (0, import_child_process.execFile)(whichCmd, [cmd], (err, stdout) => {
        if (err) {
          resolve(null);
        } else {
          const path = stdout.trim().split("\n")[0].trim();
          resolve(path || null);
        }
      });
    });
  }
  async getVersion(cliPath) {
    const path = cliPath || this.cachedPath;
    if (!path) return "unknown";
    return new Promise((resolve) => {
      (0, import_child_process.execFile)(path, ["--version"], (err, stdout) => {
        if (err) resolve("unknown");
        else resolve(stdout.trim());
      });
    });
  }
  clearCache() {
    this.cachedPath = null;
  }
};

// src/features/settings/CodebuddianSettingsTab.ts
var CodebuddianSettingsTab = class extends import_obsidian3.PluginSettingTab {
  plugin;
  cliDetector;
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
    this.cliDetector = new CliDetector();
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Codebuddian Settings" });
    new import_obsidian3.Setting(containerEl).setName("CodeBuddy CLI path").setDesc("Path to codebuddy binary. Leave empty for auto-detection.").addText((text) => text.setPlaceholder("Auto-detect").setValue(this.plugin.settings.cliPath).onChange(async (value) => {
      this.plugin.settings.cliPath = value;
      await this.plugin.saveSettings();
    })).addButton((btn) => btn.setButtonText("Detect").onClick(async () => {
      const path = await this.cliDetector.detect();
      if (path) {
        this.plugin.settings.cliPath = path;
        await this.plugin.saveSettings();
        this.display();
        new import_obsidian3.Notice(`Found: ${path}`);
      } else {
        new import_obsidian3.Notice("CodeBuddy CLI not found");
      }
    }));
    new import_obsidian3.Setting(containerEl).setName("Model").setDesc("Default model for CodeBuddy sessions").addText((text) => text.setPlaceholder("auto").setValue(this.plugin.settings.model).onChange(async (value) => {
      this.plugin.settings.model = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Permission mode").setDesc("Default permission mode for tool approvals").addDropdown((dropdown) => dropdown.addOptions({
      "default": "Default (ask for approval)",
      "acceptEdits": "Accept Edits (auto-approve file edits)",
      "plan": "Plan Mode (explore first)",
      "bypassPermissions": "Bypass All (\u26A0\uFE0F dangerous)"
    }).setValue(this.plugin.settings.permissionMode).onChange(async (value) => {
      this.plugin.settings.permissionMode = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Append system prompt").setDesc("Additional system prompt appended to every session").addTextArea((text) => text.setPlaceholder("Additional instructions for CodeBuddy\u2026").setValue(this.plugin.settings.appendSystemPrompt).onChange(async (value) => {
      this.plugin.settings.appendSystemPrompt = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("MCP config path").setDesc("Path to MCP servers config file (relative to vault root)").addText((text) => text.setPlaceholder(".codebuddian/mcp.json").setValue(this.plugin.settings.mcpConfigPath).onChange(async (value) => {
      this.plugin.settings.mcpConfigPath = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Additional directories").setDesc("Extra directories to allow tool access (comma-separated)").addText((text) => text.setPlaceholder("/path/to/dir1, /path/to/dir2").setValue(this.plugin.settings.addDirs.join(", ")).onChange(async (value) => {
      this.plugin.settings.addDirs = value.split(",").map((s) => s.trim()).filter(Boolean);
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Max turns").setDesc("Maximum agentic turns per session (0 = unlimited)").addText((text) => text.setValue(String(this.plugin.settings.maxTurns)).onChange(async (value) => {
      this.plugin.settings.maxTurns = parseInt(value) || 0;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Reasoning effort").setDesc("Reasoning effort level").addDropdown((dropdown) => dropdown.addOptions({
      "minimal": "Minimal",
      "low": "Low",
      "medium": "Medium",
      "high": "High",
      "xhigh": "Extra High",
      "max": "Maximum"
    }).setValue(this.plugin.settings.effort).onChange(async (value) => {
      this.plugin.settings.effort = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Debug mode").setDesc("Enable CLI debug output").addToggle((toggle) => toggle.setValue(this.plugin.settings.debugMode).onChange(async (value) => {
      this.plugin.settings.debugMode = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Auto-detect CLI").setDesc("Automatically detect CodeBuddy CLI path on startup").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoDetectCli).onChange(async (value) => {
      this.plugin.settings.autoDetectCli = value;
      await this.plugin.saveSettings();
    }));
  }
};

// src/core/providers/ProviderRegistry.ts
var ProviderRegistry = class {
  providers = /* @__PURE__ */ new Map();
  instances = /* @__PURE__ */ new Map();
  activeProviderId = null;
  register(descriptor, factory) {
    this.providers.set(descriptor.id, { descriptor, factory });
    if (!this.activeProviderId) {
      this.activeProviderId = descriptor.id;
    }
  }
  get(id) {
    if (!this.instances.has(id)) {
      const entry = this.providers.get(id);
      if (entry) {
        this.instances.set(id, entry.factory());
      }
    }
    return this.instances.get(id);
  }
  getDescriptor(id) {
    return this.providers.get(id)?.descriptor;
  }
  getAllDescriptors() {
    return Array.from(this.providers.values()).map((e) => e.descriptor);
  }
  getActive() {
    return this.activeProviderId ? this.get(this.activeProviderId) ?? null : null;
  }
  getActiveId() {
    return this.activeProviderId;
  }
  setActive(id) {
    if (!this.providers.has(id)) {
      throw new Error(`Provider not found: ${id}`);
    }
    this.activeProviderId = id;
  }
  async disposeAll() {
    for (const runtime of this.instances.values()) {
      await runtime.dispose();
    }
    this.instances.clear();
  }
};

// src/core/security/ApprovalManager.ts
var ApprovalManager = class {
  callback = null;
  pendingApprovals = /* @__PURE__ */ new Map();
  setCallback(cb) {
    this.callback = cb;
  }
  async requestApproval(req) {
    if (!this.callback) {
      return { id: req.id, approved: true };
    }
    return new Promise((resolve) => {
      this.pendingApprovals.set(req.id, { request: req, resolve });
      const cb = this.callback;
      if (cb) {
        cb(req).then((result) => {
          this.pendingApprovals.delete(req.id);
          resolve(result);
        });
      }
    });
  }
  cancelAll() {
    for (const [id, { resolve }] of this.pendingApprovals) {
      resolve({ id, approved: false });
    }
    this.pendingApprovals.clear();
  }
  get pendingCount() {
    return this.pendingApprovals.size;
  }
};

// src/shared/icons.ts
var import_obsidian4 = require("obsidian");
function registerIcons() {
  (0, import_obsidian4.addIcon)("codebuddian-icon", `
		<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
			<rect x="10" y="10" width="80" height="80" rx="15" fill="currentColor" opacity="0.15"/>
			<text x="50" y="65" font-size="50" text-anchor="middle" fill="currentColor">\u{1F916}</text>
		</svg>
	`);
}

// src/utils/logger.ts
var Logger = class {
  level;
  constructor(level = 1 /* INFO */) {
    this.level = level;
  }
  setLevel(level) {
    this.level = level;
  }
  debug(msg, ...args) {
    if (this.level <= 0 /* DEBUG */) {
      console.debug(`[Codebuddian] ${msg}`, ...args);
    }
  }
  info(msg, ...args) {
    if (this.level <= 1 /* INFO */) {
      console.info(`[Codebuddian] ${msg}`, ...args);
    }
  }
  warn(msg, ...args) {
    if (this.level <= 2 /* WARN */) {
      console.warn(`[Codebuddian] ${msg}`, ...args);
    }
  }
  error(msg, ...args) {
    if (this.level <= 3 /* ERROR */) {
      console.error(`[Codebuddian] ${msg}`, ...args);
    }
  }
};
var logger = new Logger();

// src/providers/codebuddy/transport-acp.ts
var import_child_process2 = require("child_process");
var import_readline = require("readline");
init_env();
var AcpTransport = class {
  process = null;
  handlers = /* @__PURE__ */ new Map();
  msgIdCounter = 0;
  pendingRequests = /* @__PURE__ */ new Map();
  buffer = "";
  _isRunning = false;
  get isRunning() {
    return this._isRunning;
  }
  async start(cliPath, opts) {
    if (this.process) {
      await this.stop();
    }
    const args = this.buildArgs(opts);
    const env = buildChildEnv(opts);
    this.process = (0, import_child_process2.spawn)(cliPath, args, {
      cwd: opts.cwd,
      env,
      stdio: ["pipe", "pipe", "pipe"]
    });
    this._isRunning = true;
    this.process.on("error", (err) => {
      this._isRunning = false;
      this.emit("error", { type: "error", data: err.message, timestamp: Date.now() });
    });
    this.process.on("exit", (code) => {
      this._isRunning = false;
      this.emit("end", { type: "end", data: { exitCode: code }, timestamp: Date.now() });
    });
    const rl = (0, import_readline.createInterface)({ input: this.process.stdout });
    rl.on("line", (line) => {
      if (!line.trim()) return;
      try {
        const msg = JSON.parse(line);
        this.handleMessage(msg);
      } catch (e) {
        this.emit("message", { type: "message", data: { raw: line }, timestamp: Date.now() });
      }
    });
    const errRl = (0, import_readline.createInterface)({ input: this.process.stderr });
    errRl.on("line", (line) => {
      this.emit("error", { type: "error", data: { stderr: line }, timestamp: Date.now() });
    });
  }
  async stop() {
    if (!this.process) return;
    this._isRunning = false;
    return new Promise((resolve) => {
      const proc = this.process;
      const timeout = setTimeout(() => {
        proc.kill("SIGKILL");
        resolve();
      }, 5e3);
      proc.on("exit", () => {
        clearTimeout(timeout);
        resolve();
      });
      proc.kill("SIGTERM");
      this.process = null;
    });
  }
  sendRequest(method, params) {
    if (!this.process || !this._isRunning) {
      return Promise.reject(new Error("ACP transport not running"));
    }
    const id = ++this.msgIdCounter;
    const msg = {
      jsonrpc: "2.0",
      id,
      method,
      params
    };
    return new Promise((resolve, reject) => {
      this.pendingRequests.set(id, { resolve, reject });
      const data = JSON.stringify(msg) + "\n";
      this.process.stdin.write(data, (err) => {
        if (err) {
          this.pendingRequests.delete(id);
          reject(err);
        }
      });
    });
  }
  sendNotification(method, params) {
    if (!this.process || !this._isRunning) return;
    const msg = {
      jsonrpc: "2.0",
      method,
      params
    };
    const data = JSON.stringify(msg) + "\n";
    this.process.stdin.write(data);
  }
  on(evt, handler) {
    if (!this.handlers.has(evt)) {
      this.handlers.set(evt, /* @__PURE__ */ new Set());
    }
    this.handlers.get(evt).add(handler);
    return () => this.handlers.get(evt)?.delete(handler);
  }
  emit(evt, event) {
    this.handlers.get(evt)?.forEach((h) => h(event));
    this.handlers.get("*")?.forEach((h) => h(event));
  }
  handleMessage(msg) {
    if (msg.id !== void 0 && this.pendingRequests.has(msg.id)) {
      const pending = this.pendingRequests.get(msg.id);
      this.pendingRequests.delete(msg.id);
      if (msg.error) {
        pending.reject(new Error(msg.error.message));
      } else {
        pending.resolve(msg.result);
      }
      return;
    }
    if (msg.method) {
      const event = this.acpMethodToEvent(msg.method, msg.params);
      if (event) {
        this.emit(event.type, event);
      }
    }
  }
  acpMethodToEvent(method, params) {
    const ts = Date.now();
    switch (method) {
      case "session/update":
      case "agent/message":
        return { type: "message", data: params, timestamp: ts };
      case "tool/use":
        return { type: "tool_use", data: params, timestamp: ts };
      case "tool/result":
        return { type: "tool_result", data: params, timestamp: ts };
      case "approval/request":
        return { type: "approval", data: params, timestamp: ts };
      case "thinking":
        return { type: "thinking", data: params, timestamp: ts };
      case "session/end":
        return { type: "end", data: params, timestamp: ts };
      case "turn/end":
        return { type: "turn_end", data: params, timestamp: ts };
      default:
        return { type: "message", data: { method, params }, timestamp: ts };
    }
  }
  buildArgs(opts) {
    const args = ["--acp", "--acp-transport", "stdio"];
    if (opts.sessionId) args.push("--session-id", opts.sessionId);
    if (opts.resume) args.push("--resume", opts.resume);
    if (opts.model) args.push("--model", opts.model);
    if (opts.permissionMode) args.push("--permission-mode", opts.permissionMode);
    if (opts.systemPromptFile) args.push("--system-prompt-file", opts.systemPromptFile);
    if (opts.appendSystemPrompt) args.push("--append-system-prompt", opts.appendSystemPrompt);
    if (opts.mcpConfigPath) args.push("--mcp-config", opts.mcpConfigPath);
    if (opts.addDirs && opts.addDirs.length > 0) args.push("--add-dir", ...opts.addDirs);
    if (opts.allowedTools && opts.allowedTools.length > 0) args.push("--allowedTools", ...opts.allowedTools);
    if (opts.disallowedTools && opts.disallowedTools.length > 0) args.push("--disallowedTools", ...opts.disallowedTools);
    if (opts.maxTurns && opts.maxTurns > 0) args.push("--max-turns", String(opts.maxTurns));
    if (opts.effort) args.push("--effort", opts.effort);
    if (opts.includePartialMessages) args.push("--include-partial-messages");
    if (opts.strictMcpConfig) args.push("--strict-mcp-config");
    if (opts.debug) args.push("--debug");
    if (opts.verbose) args.push("--verbose");
    return args;
  }
};

// src/core/prompt/mainAgent.ts
var PromptCompiler = class {
  constructor(settings, vaultPath) {
    this.settings = settings;
    this.vaultPath = vaultPath;
  }
  compile(input) {
    const parts = [];
    if (this.settings.appendSystemPrompt) {
      parts.push(this.settings.appendSystemPrompt);
    }
    if (input.instruction) {
      parts.push(`
[Instruction]: ${input.instruction}`);
    }
    if (input.mentions && input.mentions.length > 0) {
      const mentionParts = [];
      for (const mention of input.mentions) {
        mentionParts.push(this.resolveMention(mention));
      }
      if (mentionParts.length > 0) {
        parts.push(`
[Referenced files]:
${mentionParts.join("\n")}`);
      }
    }
    parts.push(input.text);
    return parts.join("\n");
  }
  resolveMention(mention) {
    switch (mention.type) {
      case "file":
        return `- @${mention.ref}`;
      case "mcp":
        return `- @mcp:${mention.ref}`;
      case "agent":
        return `- @agent:${mention.ref}`;
      case "extDir":
        return `- @dir:${mention.ref}`;
      default:
        return `- @${mention.ref}`;
    }
  }
};

// src/providers/codebuddy/index.ts
var CODEBUDDY_PROVIDER = {
  id: "codebuddy",
  displayName: "CodeBuddy",
  description: "CodeBuddy CLI \u2013 AI coding agent with ACP protocol",
  icon: "\u{1F916}",
  capabilities: {
    chat: true,
    inlineEdit: true,
    planMode: true,
    mcp: true,
    resume: true,
    slashCommands: true,
    skills: true,
    agents: true
  }
};

// src/providers/codebuddy/runtime/CodebuddyChatRuntime.ts
var CodebuddyChatRuntime = class {
  descriptor = CODEBUDDY_PROVIDER;
  transport;
  cliDetector;
  promptCompiler;
  approvalManager;
  settings;
  currentSession = null;
  state;
  constructor(settings, approvalManager, vaultPath) {
    this.settings = settings;
    this.transport = new AcpTransport();
    this.cliDetector = new CliDetector();
    this.promptCompiler = new PromptCompiler(settings, vaultPath);
    this.approvalManager = approvalManager;
    this.state = {
      cliPath: "",
      cliVersion: "",
      isInstalled: false,
      model: settings.model,
      sessionId: null
    };
  }
  async start(opts) {
    const cliPath = await this.resolveCliPath();
    const launchOpts = {
      cwd: opts.cwd,
      sessionId: opts.sessionId,
      resume: opts.resume,
      model: opts.model || this.settings.model || void 0,
      permissionMode: opts.permissionMode || this.settings.permissionMode,
      allowedTools: opts.allowedTools || (this.settings.allowedTools.length > 0 ? this.settings.allowedTools : void 0),
      disallowedTools: opts.disallowedTools || (this.settings.disallowedTools.length > 0 ? this.settings.disallowedTools : void 0),
      systemPromptFile: opts.systemPromptFile || this.settings.systemPromptFile || void 0,
      appendSystemPrompt: opts.appendSystemPrompt || this.settings.appendSystemPrompt || void 0,
      mcpConfigPath: opts.mcpConfigPath || this.settings.mcpConfigPath || void 0,
      addDirs: opts.addDirs || (this.settings.addDirs.length > 0 ? this.settings.addDirs : void 0),
      maxTurns: opts.maxTurns || this.settings.maxTurns || void 0,
      effort: opts.effort || this.settings.effort || void 0,
      includePartialMessages: this.settings.includePartialMessages,
      strictMcpConfig: this.settings.strictMcpConfig,
      debug: this.settings.debugMode,
      verbose: this.settings.verboseMode
    };
    await this.transport.start(cliPath, launchOpts);
    const sessionId = opts.sessionId || this.generateSessionId();
    this.state.sessionId = sessionId;
    this.currentSession = new SessionHandleImpl(
      sessionId,
      this.transport,
      this.promptCompiler,
      this.approvalManager
    );
    this.transport.on("approval", (event) => {
      this.handleApprovalEvent(event);
    });
    return this.currentSession;
  }
  getActiveSession() {
    return this.currentSession;
  }
  getState() {
    return { ...this.state };
  }
  async dispose() {
    await this.transport.stop();
    this.currentSession = null;
  }
  async resolveCliPath() {
    if (this.settings.cliPath) {
      return this.settings.cliPath;
    }
    if (this.settings.autoDetectCli) {
      const detected = await this.cliDetector.detect();
      if (detected) {
        this.state.cliPath = detected;
        this.state.isInstalled = true;
        this.state.cliVersion = await this.cliDetector.getVersion(detected);
        return detected;
      }
    }
    throw new Error(
      "CodeBuddy CLI not found. Please install it or set the path in Settings.\nInstall: npm install -g @tencent-ai/codebuddy-code\nOr set the path manually in Codebuddian settings."
    );
  }
  async handleApprovalEvent(event) {
    const data = event.data;
    if (!data.id) return;
    const result = await this.approvalManager.requestApproval({
      id: data.id,
      tool: data.tool || "unknown",
      args: data.args || {},
      description: data.description || `Allow ${data.tool}?`,
      riskLevel: this.assessRisk(data.tool)
    });
    this.transport.sendNotification("approval/response", {
      id: data.id,
      approved: result.approved,
      modifiedArgs: result.modifiedArgs
    });
  }
  assessRisk(tool) {
    if (!tool) return "medium";
    const highRisk = ["Bash", "Write", "Edit"];
    const mediumRisk = ["WebFetch", "WebSearch", "ImageGen"];
    if (highRisk.includes(tool)) return "high";
    if (mediumRisk.includes(tool)) return "medium";
    return "low";
  }
  generateSessionId() {
    return `cb-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  }
};
var SessionHandleImpl = class {
  constructor(sessionId, transport, promptCompiler, approvalManager) {
    this.sessionId = sessionId;
    this.transport = transport;
    this.promptCompiler = promptCompiler;
    this.approvalManager = approvalManager;
  }
  _status = "running";
  unsubscribeFns = [];
  get status() {
    return this._status;
  }
  async send(input) {
    const compiledPrompt = this.promptCompiler.compile(input);
    this.transport.sendNotification("user/message", {
      content: compiledPrompt,
      mentions: input.mentions,
      attachments: input.attachments,
      permissionMode: input.permissionMode
    });
  }
  async cancel() {
    this.transport.sendNotification("session/cancel");
    this._status = "idle";
  }
  async resume(sessionId) {
    this.transport.sendNotification("session/resume", { sessionId });
    this._status = "running";
  }
  async fork() {
    const newId = `cb-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
    this.transport.sendNotification("session/fork", { newSessionId: newId });
    return newId;
  }
  async rewind() {
    this.transport.sendNotification("session/rewind");
  }
  on(evt, cb) {
    const unsub = this.transport.on(evt, cb);
    this.unsubscribeFns.push(unsub);
    return unsub;
  }
  async close() {
    for (const unsub of this.unsubscribeFns) {
      unsub();
    }
    this.unsubscribeFns = [];
    this._status = "idle";
  }
};

// src/providers/codebuddy/registration.ts
function createCodebuddyRegistration(getSettings, approvalManager, vaultPath) {
  return {
    descriptor: CODEBUDDY_PROVIDER,
    factory: (settings) => {
      return new CodebuddyChatRuntime(settings, approvalManager, vaultPath);
    }
  };
}

// src/main.ts
var CodebuddianPlugin = class extends import_obsidian6.Plugin {
  settings = DEFAULT_SETTINGS;
  providerRegistry;
  approvalManager;
  chatView = null;
  async onload() {
    await this.loadSettings();
    logger.setLevel(this.settings.debugMode ? 0 /* DEBUG */ : 1 /* INFO */);
    const locale = window.navigator.language || "en";
    setLocale(locale.startsWith("zh") ? "zh-CN" : "en");
    registerIcons();
    this.providerRegistry = new ProviderRegistry();
    this.approvalManager = new ApprovalManager();
    const vaultPath = this.app.vault.adapter.getBasePath?.() ?? "";
    const codebuddyRegistration = createCodebuddyRegistration(
      () => this.settings,
      this.approvalManager,
      vaultPath
    );
    this.providerRegistry.register(
      codebuddyRegistration.descriptor,
      () => codebuddyRegistration.factory(this.settings)
    );
    this.registerView(CHAT_VIEW_TYPE, (leaf) => {
      this.chatView = new CodebuddianChatView(leaf);
      const runtime = this.providerRegistry.getActive();
      if (runtime) {
        this.chatView.setRuntime(runtime);
      }
      return this.chatView;
    });
    this.addRibbonIcon("message-circle", "Codebuddian", () => {
      this.activateChatView();
    });
    this.addCommand({
      id: "codebuddian.open-chat",
      name: "Open chat",
      callback: () => this.activateChatView()
    });
    this.addCommand({
      id: "codebuddian.new-chat",
      name: "New chat tab",
      callback: () => {
        this.activateChatView();
      }
    });
    this.addCommand({
      id: "codebuddian.inline-edit",
      name: "Inline edit selection",
      callback: () => this.handleInlineEdit()
    });
    this.addCommand({
      id: "codebuddian.toggle-plan-mode",
      name: "Toggle plan mode",
      callback: () => {
        new import_obsidian6.Notice("Plan mode toggled");
      }
    });
    this.addCommand({
      id: "codebuddian.cancel-current-turn",
      name: "Cancel current turn",
      callback: () => {
        new import_obsidian6.Notice("Current turn cancelled");
      }
    });
    this.addSettingTab(new CodebuddianSettingsTab(this.app, this));
    logger.info("Codebuddian plugin loaded");
  }
  async onunload() {
    await this.providerRegistry.disposeAll();
    this.chatView = null;
    logger.info("Codebuddian plugin unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async activateChatView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(CHAT_VIEW_TYPE)[0];
    if (!leaf) {
      const rightLeaf = workspace.getRightLeaf(false);
      if (rightLeaf) {
        await rightLeaf.setViewState({ type: CHAT_VIEW_TYPE, active: true });
        leaf = rightLeaf;
      }
    } else {
      workspace.revealLeaf(leaf);
    }
  }
  async handleInlineEdit() {
    const activeView = this.app.workspace.getActiveViewOfType(
      (await import("obsidian")).MarkdownView
    );
    if (!activeView) {
      new import_obsidian6.Notice("No active markdown view");
      return;
    }
    const selection = activeView.editor.getSelection();
    if (!selection) {
      new import_obsidian6.Notice("No text selected");
      return;
    }
    const prompt = "Improve this text";
    const { InlineEditModal: InlineEditModal2 } = await Promise.resolve().then(() => (init_InlineEditModal(), InlineEditModal_exports));
    const vaultPath = this.app.vault.adapter.getBasePath?.() ?? "";
    const cliPath = this.settings.cliPath || "codebuddy";
    const modal = new InlineEditModal2(this.app, {
      originalText: selection,
      prompt,
      settings: this.settings,
      cliPath,
      vaultPath,
      onApply: (newText) => {
        activeView.editor.replaceSelection(newText);
        new import_obsidian6.Notice("Changes applied");
      }
    });
    modal.open();
  }
};
var main_default = CodebuddianPlugin;
